image: devwithlando/gitpod:1
# https://github.com/lando/drupal-dev-environment/blob/9.4.x/.gitpod.yml

tasks:
  - name: Drupal start
    init: |
      wget -O web/sites/default/settings.local.php https://www.dropbox.com/s/yxrzeaw3fl4vi7n/settings.local.php
      wget $BIII_DATABASE_URL
      lando start
      lando rebuild
      lando composer install
      git checkout web/.htaccess
      lando db-import $(echo $BIII_DATABASE_URL | sed -e 's/.*\///')
      lando drush cr
      #lando drush si -y --account-pass=admin --site-name='gitpod_lando' demo_umami
      gp preview $(gp url $(lando info --format=json | jq -r ".[0].urls[1]" | sed -e 's#http://localhost:\(\)#\1#'))
      lando ssh --service appserver --user root --command "apt-get update && apt install vim -y"

vscode:
  extensions:
    - felixfbecker.php-debug
    - dbaeumer.vscode-eslint
    - eamodio.gitlens
    - EditorConfig.EditorConfig
    - esbenp.prettier-vscode
    - stylelint.vscode-stylelint
    - tombonnike.vscode-status-bar-format-toggle
    - usernamehw.errorlens
    - mblode.twig-language
    - skippednote.vs-code-drupal
