image:
  file: .gitpod.Dockerfile

tasks:
  - name: Drupal start
    init: |
      wget -O web/sites/default/settings.local.php https://www.dropbox.com/s/yxrzeaw3fl4vi7n/settings.local.php
      wget https://www.dropbox.com/s/3dgun9osw5te17b/20210916dev.sql.gz
      lando start
      lando composer install
      git checkout web/.htaccess
      lando db-import 20210916dev.sql.gz
      lando drush cr
      #lando drush si -y --account-pass=admin --site-name='gitpod_lando' demo_umami
      gp preview $(gp url $(lando info --format=json | jq -r ".[0].urls[1]" | sed -e 's#http://localhost:\(\)#\1#'))

vscode:
  extensions:
    - felixfbecker.php-debug
    - dbaeumer.vscode-eslint
    - eamodio.gitlens
    - EditorConfig.EditorConfig
    - esbenp.prettier-vscode
    - stylelint.vscode-stylelint
    - tombonnike.vscode-status-bar-format-toggle
    - usernamehw.errorlens
    - mblode.twig-language
    - skippednote.vs-code-drupal
