name: bisedev
recipe: drupal8
compose:
  - docker-compose.network-mtu.yml
config:
  webroot: web
  php: '8.0'
  composer_version: '2.5.5'
services:
  appserver:
    ssl: false
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
