language: php
dist: trusty
sudo: required

services:
  - docker

php:
  - 7.1

env:
  global:
    - DRUPAL_BASE_URL="http://127.0.0.1:8080"
  matrix:
    - JOB=job:check-coding-standards
    - JOB=job:run-unit-tests
    #- JOB=job:run-behat-tests

before_install:
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
  - composer --verbose install

before_script:
  - cp .travis/RoboFile.php .

script:
  - vendor/bin/robo $JOB

after_success:
  - test $JOB = "job:run-unit-tests" && travis_retry php vendor/bin/php-coveralls -v
